// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class AccountPostPcs
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string WarehouseCode { get; set; }
        public string DisplayName { get; set; }
        public int? WarehouseId { get; set; }
        public bool? IsHaNoi { get; set; }
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
        public string GrantType { get; set; }
        public string Scope { get; set; }
        public int? PostOfficesDefault { get; set; }

        public virtual Warehouse Warehouse { get; set; }
    }
}