// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class BinLocation
    {
        public BinLocation()
        {
            Container = new HashSet<Container>();
            Hawb = new HashSet<Hawb>();
            Package = new HashSet<Package>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public int? Row { get; set; }
        public int? Column { get; set; }
        public decimal? Height { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public int Status { get; set; }
        public decimal? Weight { get; set; }
        public decimal? Length { get; set; }
        public decimal? Width { get; set; }
        public int? Type { get; set; }
        public int? MaximumPosition { get; set; }
        public int? CountPackages { get; set; }
        public decimal? MaximumWeight { get; set; }
        public decimal? MinimumWeight { get; set; }
        public int? ShippingRouteId { get; set; }

        public virtual ShippingRoute ShippingRoute { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual ICollection<Container> Container { get; set; }
        public virtual ICollection<Hawb> Hawb { get; set; }
        public virtual ICollection<Package> Package { get; set; }
    }
}