// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class Category
    {
        public Category()
        {
            Product = new HashSet<Product>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Logos { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public int? Status { get; set; }
        public int? CategoryGroupId { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitleJp { get; set; }
        public int? Order { get; set; }
        public string Elements { get; set; }

        public virtual CategoryGroup CategoryGroup { get; set; }
        public virtual WarningInfo WarningInfo { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}