// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class CategoryGroup
    {
        public CategoryGroup()
        {
            Category = new HashSet<Category>();
        }

        public int Id { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string NameEn { get; set; }
        public string NameJp { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionJp { get; set; }

        public virtual ICollection<Category> Category { get; set; }
    }
}