// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class Container
    {
        public Container()
        {
            Package = new HashSet<Package>();
        }

        public int Id { get; set; }
        public int? RefId { get; set; }
        public string Code { get; set; }
        public string CodeCustom { get; set; }
        public string Name { get; set; }
        public int NoOfPiece { get; set; }
        public decimal Weight { get; set; }
        public decimal? DimensionWeight { get; set; }
        public decimal Length { get; set; }
        public decimal Width { get; set; }
        public decimal Height { get; set; }
        public int? WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public int? FlightId { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public int Status { get; set; }
        public int? BinLocationId { get; set; }
        public string Region { get; set; }
        public bool? Lock { get; set; }
        public string LastBinLocation { get; set; }
        public decimal CrateWeight { get; set; }

        public virtual BinLocation BinLocation { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual ICollection<Package> Package { get; set; }
    }
}