// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class EmsServiceCharge
    {
        public int Id { get; set; }
        public int? FromWeight { get; set; }
        public int? ToWeight { get; set; }
        public int? PriceAreaOne { get; set; }
        public int? PriceAreaTwo { get; set; }
        public int? PriceAreaTwoSub { get; set; }
        public int? PriceAreaThree { get; set; }
        public int? NextWeight { get; set; }
        public int? NextPrice { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}