// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class EmsShippingState
    {
        public int Id { get; set; }
        public int PackageDetailQuoteId { get; set; }
        public string TrackingCode { get; set; }
        public string OrderCode { get; set; }
        public string StatusCode { get; set; }
        public string StatusName { get; set; }
        public string Note { get; set; }
        public string Locate { get; set; }
        public string Datetime { get; set; }
        public int? TotalWeight { get; set; }
        public string Transaction { get; set; }
        public string RawData { get; set; }

        public virtual Shipment PackageDetailQuote { get; set; }
    }
}