// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class Flight
    {
        public Flight()
        {
            Container = new HashSet<Container>();
            Hawb = new HashSet<Hawb>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public decimal? Weight { get; set; }
        public string Departure { get; set; }
        public string Destination { get; set; }
        public string File { get; set; }
        public string WarehouseCode { get; set; }
        public int? WarehouseId { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public int Status { get; set; }
        public string CreatedWarehouseCode { get; set; }
        public int? CreatedWarehouseId { get; set; }
        public int? Type { get; set; }
        public bool? Lock { get; set; }
        public DateTime? DateArrival { get; set; }
        public decimal? ActualWeight { get; set; }
        public DateTime? ExploitCompletedDate { get; set; }
        public decimal? WeightBulky { get; set; }

        public virtual ICollection<Container> Container { get; set; }
        public virtual ICollection<Hawb> Hawb { get; set; }
    }
}