// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class Hawb
    {
        public Hawb()
        {
            Package = new HashSet<Package>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string WarehouseCode { get; set; }
        public decimal? Length { get; set; }
        public decimal? Width { get; set; }
        public decimal? Height { get; set; }
        public decimal? Weight { get; set; }
        public string ImporterName { get; set; }
        public string ImporterAddress { get; set; }
        public string ImporterPhone { get; set; }
        public string ImporterPersonInCharge { get; set; }
        public string ImportDuty { get; set; }
        public string ImportCurrencyCode { get; set; }
        public string ImportNote { get; set; }
        public string ExporterName { get; set; }
        public string ExporterAddress { get; set; }
        public string ExporterPhone { get; set; }
        public string ExporterPersonInCharge { get; set; }
        public string ExportDuty { get; set; }
        public string ExportCurrencyCode { get; set; }
        public string ExportNote { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public int? Status { get; set; }
        public string Name { get; set; }
        public int? WarehouseId { get; set; }
        public int? BinLocationId { get; set; }
        public int? FlightId { get; set; }
        public int? NoOfPiece { get; set; }

        public virtual BinLocation BinLocation { get; set; }
        public virtual Flight Flight { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual ICollection<Package> Package { get; set; }
    }
}