// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class Package
    {
        public Package()
        {
            InverseParent = new HashSet<Package>();
            PackageDetailMapping = new HashSet<PackageDetailMapping>();
            Product = new HashSet<Product>();
        }

        public int Id { get; set; }
        public int? RefId { get; set; }
        public string Code { get; set; }
        public string TrackingCode { get; set; }
        public string TransportCode { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public decimal? Weight { get; set; }
        public decimal? Length { get; set; }
        public decimal? Width { get; set; }
        public decimal? Height { get; set; }
        public int? NoOfPiece { get; set; }
        public decimal? DimensionWeight { get; set; }
        public decimal? CodFee { get; set; }
        public string CodProof { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public int? Property { get; set; }
        public int Status { get; set; }
        public int? ContainerId { get; set; }
        public int? WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public int? BinLocationId { get; set; }
        public string Region { get; set; }
        public string ServiceChargeCode { get; set; }
        public int? SyncStatus { get; set; }
        public DateTime? LastSyncDate { get; set; }
        public string History { get; set; }
        public string EmployeeHandling { get; set; }
        public DateTime? ProcessedDate { get; set; }
        public string ImageBalanceScale { get; set; }
        public int? FlightId { get; set; }
        public int? RefPackageId { get; set; }
        public bool? HasComplain { get; set; }
        public int? WarningLevel { get; set; }
        public string LastBinLocation { get; set; }
        public string ChildIds { get; set; }
        public string FlightCode { get; set; }
        public string FlightName { get; set; }
        public string ContainerCode { get; set; }
        public string ContainerName { get; set; }
        public int? ServiceStatus { get; set; }
        public int? HawbId { get; set; }
        public string HawbCode { get; set; }
        public string HawbName { get; set; }
        public int? WeightType { get; set; }
        public string TrackingNote { get; set; }
        public string Note { get; set; }
        public bool? IsNoTracking { get; set; }
        public string ProcessedEmployee { get; set; }
        public string SubTracking { get; set; }
        public string Logs { get; set; }

        public virtual BinLocation BinLocation { get; set; }
        public virtual Container Container { get; set; }
        public virtual Hawb Hawb { get; set; }
        public virtual Package Parent { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual ICollection<Package> InverseParent { get; set; }
        public virtual ICollection<PackageDetailMapping> PackageDetailMapping { get; set; }
        public virtual ICollection<Product> Product { get; set; }
    }
}