// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class PackageDetail
    {
        public PackageDetail()
        {
            PackageDetailMapping = new HashSet<PackageDetailMapping>();
            Product = new HashSet<Product>();
            ServiceChargePackageMapping = new HashSet<ServiceChargePackageMapping>();
        }

        public int Id { get; set; }
        public int? RefId { get; set; }
        public int? WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public string OrderCode { get; set; }
        public int? OrderWarning { get; set; }
        public int? PackageDetailQuoteId { get; set; }
        public string DeliveryBillCode { get; set; }
        public string OrderType { get; set; }
        public DateTime? OrderDate { get; set; }
        public string Title { get; set; }
        public decimal? Total { get; set; }
        public int? BuyFee { get; set; }
        public decimal? ShippingUnitGlobal { get; set; }
        public decimal? ShippingFee { get; set; }
        public decimal? Paid { get; set; }
        public decimal? Weight { get; set; }
        public decimal? Length { get; set; }
        public decimal? Width { get; set; }
        public decimal? Height { get; set; }
        public string CustomerId { get; set; }
        public string CurrencyCode { get; set; }
        public decimal? CurrencyRate { get; set; }
        public string CustomerDistrict { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerName { get; set; }
        public string CustomerProvince { get; set; }
        public string CustomerWard { get; set; }
        public string History { get; set; }
        public string Region { get; set; }
        public int? BinLocationId { get; set; }
        public string OrderStatus { get; set; }
        public int? Status { get; set; }
        public decimal? Surcharge { get; set; }
        public string SurchargeNote { get; set; }
        public DateTime? ProcessedDate { get; set; }
        public string EmployeeHandling { get; set; }
        public string ImageBalanceScale { get; set; }
        public int? RefOrderId { get; set; }
        public int? PackageId { get; set; }
        public decimal? TotalAmount { get; set; }
        public decimal? TotalAdditional { get; set; }
        public decimal? ShippingFeeDomestic { get; set; }
        public decimal? WeightQuote { get; set; }
        public decimal? LengthQuote { get; set; }
        public decimal? WidthQuote { get; set; }
        public decimal? HeightQuote { get; set; }
        public bool? PaymentStatus { get; set; }
        public int? WarningLevel { get; set; }
        public string LastBinLocation { get; set; }
        public string SurchargePaymentBy { get; set; }
        public string FromRoute { get; set; }
        public string Supporter { get; set; }
        public string Mawb { get; set; }
        public bool? IsEdited { get; set; }
        public string Note { get; set; }
        public string ShippingRouteCode { get; set; }
        public int? ShippingRouteId { get; set; }
        public DateTime? ApprovalDate { get; set; }
        public bool? Crate { get; set; }

        public virtual PackageDetailQuote PackageDetailQuote { get; set; }
        public virtual ICollection<PackageDetailMapping> PackageDetailMapping { get; set; }
        public virtual ICollection<Product> Product { get; set; }
        public virtual ICollection<ServiceChargePackageMapping> ServiceChargePackageMapping { get; set; }
    }
}