// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class ProductSample
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Url { get; set; }
        public int? CategoryId { get; set; }
        public int? Origin { get; set; }
        public string Name { get; set; }
        public string NameEn { get; set; }
        public string NameJp { get; set; }
        public string Images { get; set; }
        public string ShortDescription { get; set; }
        public string ShortDescriptionEn { get; set; }
        public string ShortDescriptionJp { get; set; }
        public string FullDescription { get; set; }
        public string FullDescriptionEn { get; set; }
        public string FullDescriptionJp { get; set; }
        public decimal? Price { get; set; }
        public decimal? Tax { get; set; }
        public string ManufacturerPartNumber { get; set; }
        public decimal? Weight { get; set; }
        public decimal? Length { get; set; }
        public decimal? Width { get; set; }
        public decimal? Height { get; set; }
        public string ProductUnit { get; set; }
        public int? QtyPerUnit { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int Status { get; set; }
    }
}