// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class Product
    {
        public int Id { get; set; }
        public int? RefId { get; set; }
        public string Code { get; set; }
        public int? CategoryId { get; set; }
        public int PackageDetailId { get; set; }
        public int? PackageId { get; set; }
        public int Type { get; set; }
        public int? Origin { get; set; }
        public string Name { get; set; }
        public string NameCustom { get; set; }
        public string Images { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public decimal? Price { get; set; }
        public decimal? PriceCustom { get; set; }
        public string ManufacturerPartNumber { get; set; }
        public string UserAgreementText { get; set; }
        public decimal? Weight { get; set; }
        public decimal? Length { get; set; }
        public decimal? Width { get; set; }
        public decimal? Height { get; set; }
        public string Url { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string ProductUnit { get; set; }
        public int? QtyPerUnit { get; set; }
        public string AdminNote { get; set; }
        public string CustomerNote { get; set; }
        public string OriginCustom { get; set; }
        public decimal? Tax { get; set; }
        public int? SourceId { get; set; }
        public decimal? WeightQuote { get; set; }
        public decimal? LengthQuote { get; set; }
        public decimal? WidthQuote { get; set; }
        public decimal? HeightQuote { get; set; }
        public decimal? PriceStandard { get; set; }
        public decimal? PriceQuantity { get; set; }
        public decimal? PriceWeight { get; set; }
        public int? DataType { get; set; }
        public string ProAttribute { get; set; }

        public virtual Category Category { get; set; }
        public virtual Package Package { get; set; }
        public virtual PackageDetail PackageDetail { get; set; }
    }
}