// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class ServiceChargePackageMapping
    {
        public int PackageDetailId { get; set; }
        public int ServiceChargeId { get; set; }
        public decimal? Price { get; set; }
        public string Note { get; set; }
        public string Images { get; set; }
        public decimal? Percent { get; set; }
        public DateTime? EstimateTime { get; set; }
        public int Status { get; set; }
        public string PaymentBy { get; set; }
        public decimal? PaymentActuallyMoneyCollect { get; set; }

        public virtual PackageDetail PackageDetail { get; set; }
        public virtual ServiceCharge ServiceCharge { get; set; }
    }
}