// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class ServiceCharge
    {
        public ServiceCharge()
        {
            ServiceChargePackageMapping = new HashSet<ServiceChargePackageMapping>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? FromDate { get; set; }
        public DateTime? ToDate { get; set; }
        public decimal? Price { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public int Status { get; set; }
        public string Unit { get; set; }
        public int? PriceType { get; set; }
        public string NameEn { get; set; }
        public string NameJp { get; set; }
        public string DescriptionEn { get; set; }
        public string DescriptionJp { get; set; }
        public string UnitEn { get; set; }
        public string UnitJp { get; set; }
        public string WarehouseCode { get; set; }
        public int? WarehouseId { get; set; }
        public string CreatedWarehouseCode { get; set; }
        public int? CreatedWarehouseId { get; set; }

        public virtual ICollection<ServiceChargePackageMapping> ServiceChargePackageMapping { get; set; }
    }
}