// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class ShippingRouteWarehouse
    {
        public int Id { get; set; }
        public int ShippingRouteId { get; set; }
        public int WarehouseId { get; set; }
        public string ShippingRouteCode { get; set; }
        public string WarehouseCode { get; set; }
        public bool Active { get; set; }
        public int DisplayOrder { get; set; }

        public virtual ShippingRoute ShippingRoute { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}