// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class Shipment
    {
        public Shipment()
        {
            EmsShippingState = new HashSet<EmsShippingState>();
            ShipmentStatusHistory = new HashSet<ShipmentStatusHistory>();
            VtpShippingState = new HashSet<VtpShippingState>();
        }

        public int PackageDetailQuoteId { get; set; }
        public string PoNumber { get; set; }
        public int WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        /// <summary>
        /// Đơn vị vận chuyển
        /// </summary>
        public int ShippingUnitType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CustomerId { get; set; }
        /// <summary>
        /// Tên người nhận hàng
        /// </summary>
        public string CustomerName { get; set; }
        /// <summary>
        /// Số phone nhận hàng
        /// </summary>
        public string CustomerPhone { get; set; }
        /// <summary>
        /// Địa chỉ nhận hàng
        /// </summary>
        public string CustomerAddress { get; set; }
        public string CustomerProvince { get; set; }
        /// <summary>
        /// Người đặt hàng
        /// </summary>
        public string CustomerDistrict { get; set; }
        public string CustomerWard { get; set; }
        /// <summary>
        /// Tổng tiền đơn hàng khách phải thanh toán
        /// </summary>
        public decimal TotalAmount { get; set; }
        /// <summary>
        /// Tiền COD khách phải thanh toán
        /// </summary>
        public decimal DeliveryCharge { get; set; }
        public DateTime? DeliveryEstimateTime { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        /// <summary>
        /// Loại vận chuyển
        /// </summary>
        public int? Type { get; set; }
        public int Status { get; set; }

        public virtual PackageDetailQuote PackageDetailQuote { get; set; }
        public virtual ICollection<EmsShippingState> EmsShippingState { get; set; }
        public virtual ICollection<ShipmentStatusHistory> ShipmentStatusHistory { get; set; }
        public virtual ICollection<VtpShippingState> VtpShippingState { get; set; }
    }
}