// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class ShippingRoute
    {
        public ShippingRoute()
        {
            BinLocation = new HashSet<BinLocation>();
            ShippingRouteWarehouse = new HashSet<ShippingRouteWarehouse>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int FromCountryId { get; set; }
        public int ToCountryId { get; set; }
        public bool Active { get; set; }
        public int DisplayOrder { get; set; }

        public virtual ICollection<BinLocation> BinLocation { get; set; }
        public virtual ICollection<ShippingRouteWarehouse> ShippingRouteWarehouse { get; set; }
    }
}