// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.WH.Model
{
    public partial class WarehouseEmp
    {
        public string AccountId { get; set; }
        public int WarehouseId { get; set; }
        public bool? Active { get; set; }
        public DateTime? EffectiveTime { get; set; }
        public string TakeCare { get; set; }
        public int? Productivity { get; set; }

        public virtual Warehouse Warehouse { get; set; }
    }
}