using System;
using System.Collections.Generic;

namespace iChiba.Portal.PrivateApi.AppModel.Models
{
    public class OrderViewModel
    {
        public int Id { get; set; }
        public Guid GuidId { get; set; }
        public string Title { get; set; }
        public string Operator { get; set; }
        public string Saler { get; set; }
        public int? SalerRating { get; set; }
        public int? SalerReview { get; set; }
        public string AccountId { get; set; }
        public string Code { get; set; }
        public long? ShippingUnit { get; set; }
        public long? Total { get; set; }
        public long? PriceExpected { get; set; }
        public string TrackingBox { get; set; }
        public string Tracking { get; set; }
        public string TrackingBy { get; set; }
        public DateTime? TrackingDate { get; set; }
        public string TrackingTranport { get; set; }
        public string OrderNumber { get; set; }
        public int? Status { get; set; }
        public string StatusNote { get; set; }
        public int? TrackingStatus { get; set; }
        public string OrderType { get; set; }
        public DateTime OrderDate { get; set; }
        public string PaymentBankNumber { get; set; }
        public int? PaymentType { get; set; }
        public int? PaymentDuration { get; set; }
        public string DeliveryPartner { get; set; }
        public string DdimportType { get; set; }
        public int? DeliveryType { get; set; }
        public DateTime? DeliveryExpected { get; set; }
        public DateTime? DeliveryDate { get; set; }
        public DateTime? DeliveredDate { get; set; }
        public long? DeliveryCod { get; set; }
        public string DeliveryCode { get; set; }
        public long? DeliveryFee { get; set; }
        public bool? DeliveryPayType { get; set; }
        public int? DeliveryDiscount { get; set; }
        public int? DeliverySyncStatus { get; set; }
        public DateTime? DeliverySyncWh { get; set; }
        public DateTime? SurchargeDate { get; set; }
        public string SurchargeBy { get; set; }
        public string SurchargePay { get; set; }
        public long? Surcharge { get; set; }
        public string SurchargeNote { get; set; }
        public string CustomerDistrict { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
        public string CustomerName { get; set; }
        public string CustomerProvince { get; set; }
        public string CustomerWard { get; set; }
        public string State { get; set; }
        public string Note { get; set; }
        public int? MinPayment { get; set; }
        public long? Paid { get; set; }
        public string Hash { get; set; }
        public long? BuyFee { get; set; }
        public DateTime? ShippingFeeDate { get; set; }
        public string ShippingFeeBy { get; set; }
        public long? ShippingFee { get; set; }
        public long? ShippingFeeToLocal { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ProcessDate { get; set; }
        public byte[] Version { get; set; }
        public string Warehouse { get; set; }
        public string Type { get; set; }
        public int? Weight { get; set; }
        public int? WeightOrigin { get; set; }
        public int? Width { get; set; }
        public int? Hight { get; set; }
        public int? Length { get; set; }
        public int? ExchangeRate { get; set; }
        public int? ShippingUnitGlobal { get; set; }
        public string PaymentAccount { get; set; }
        public string BidAccount { get; set; }
        public DateTime? LastSyncWh { get; set; }
        public long? TotalPayment { get; set; }
        public DateTime? EstimateTime { get; set; }
        public DateTime? LastActionDate { get; set; }
        public string LastAction { get; set; }
        public bool? Yacomplete { get; set; }
        public bool? Cod { get; set; }
        public string ProductType { get; set; }
        public bool? Negotiate { get; set; }
        public bool? BidStatus { get; set; }
        public string Images { get; set; }
        public string Payer { get; set; }
        public string PurchaseBy { get; set; }
        public DateTime? PurchaseDate { get; set; }
        public string CancelBy { get; set; }
        public DateTime? CancelDate { get; set; }
        public DateTime? CancelApproveDate { get; set; }
        public string CancelApproveBy { get; set; }
        public string AccDebit { get; set; }
        public string AccCredited { get; set; }
        public int? SyncAccStatus { get; set; }
        public DateTime? SyncAccDate { get; set; }
        public string SyncAccNo { get; set; }
        public long? StandardFee { get; set; }
        public long? AddServiceFee { get; set; }
        public DateTime? WfProcess { get; set; }
        public DateTime? CompleteDate { get; set; }
        public int? RevenueStatus { get; set; }
        public string QuoteCode { get; set; }
        public DateTime? QuoteDate { get; set; }
        public long? TotalServiceFee { get; set; }
        public string FromRoute { get; set; }
        public string Currency { get; set; }
        public string Supporter { get; set; }
        public int? CustomerRatting { get; set; }
        public DateTime? CustomerRattingDate { get; set; }
        public DateTime? WaitQuoteDate { get; set; }
        public string WhImporter { get; set; }
        public string WhExporter { get; set; }
        public string Mawb { get; set; }
        public int? TransportPaymentType { get; set; }
        public string PurchaseAssign { get; set; }
        public DateTime? RevenueDate { get; set; }
        public int? ShippingRouteId { get; set; }
        public string ShippingRouteCode { get; set; }
        public string GroupOrder { get; set; }
        public int? ToWarehouseId { get; set; }
        public string ToWarehouseCode { get; set; }
        public long? BuyServiceFee { get; set; }
        public DateTime? DepartureDate { get; set; }
        public DateTime? ShippedDate { get; set; }
        public bool? Bulky { get; set; }
        public string ProductByCustomerJson { get; set; }
        public decimal AmountVND { get; set; }

        public string CustomerFullAddress => string.Join(",", CustomerAddress, CustomerWard, CustomerDistrict, CustomerProvince);
        public List<OrderDetailViewModel> ProductViewModels { get; set; }
        public List<OrderMessageViewModel> OrderMessageViewModels { get; set; }
        public List<OrderPackageProductViewModel> ProductPackages { get; set; }
    }
}
