// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class Accaccount
    {
        public Accaccount()
        {
            InverseParentNavigation = new HashSet<Accaccount>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int? Parent { get; set; }
        public int? SyncAccStatus { get; set; }
        public DateTime? SyncAccDate { get; set; }
        public int? Status { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? ObjectMap { get; set; }
        public string BankNumber { get; set; }
        public long? UseCredited { get; set; }
        public long? UseDebit { get; set; }
        public long? BeginBalance { get; set; }
        public DateTime? BeginBalanceDate { get; set; }
        public string BeginBalanceNote { get; set; }
        public string Route { get; set; }

        public virtual Accaccount ParentNavigation { get; set; }
        public virtual ICollection<Accaccount> InverseParentNavigation { get; set; }
    }
}