// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class BankPayment
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Ftcode { get; set; }
        public long Amount { get; set; }
        public long? Fee { get; set; }
        public string TransactionType { get; set; }
        public DateTime TransactionDate { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ObjectType { get; set; }
        public string ObjectCode { get; set; }
        public string ObjectUid { get; set; }
        public int? Status { get; set; }
        public DateTime? ProcessDate { get; set; }
    }
}