// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class BankTransactionHistory
    {
        public string Id { get; set; }
        public string AccountNumber { get; set; }
        public string CreditOwner { get; set; }
        public string BankType { get; set; }
        public long DebitAmount { get; set; }
        public long CreditAmount { get; set; }
        public DateTime TransactionDate { get; set; }
        public DateTime? TransactionDateValid { get; set; }
        public string TransactionDateExtract { get; set; }
        public string Description { get; set; }
        public DateTime CreatedDate { get; set; }
        public int Status { get; set; }
        public string Hash { get; set; }
        public string Note { get; set; }
        public int? DepositStatus { get; set; }
        public int? WithdrawStatus { get; set; }
        public int? Ppstatus { get; set; }
        public int? PayStatus { get; set; }
        public int? CollectStatus { get; set; }
        public int? InTransferStatus { get; set; }
        public string CreatedBy { get; set; }
        public string HashUid { get; set; }
        public string DebitOwner { get; set; }
        public string DebitBank { get; set; }
        public int? SyncAccStatus { get; set; }
        public DateTime? SyncAccDate { get; set; }
        public string SyncAccNo { get; set; }
        public string ObjectId { get; set; }
        public string ObjectType { get; set; }
        public string ObjectCode { get; set; }
        public string AccDebit { get; set; }
        public string AccCredited { get; set; }
        public string ObjectTypeDebit { get; set; }
        public string ObjectCodeDebit { get; set; }
        public string ObjectTypeCredited { get; set; }
        public string ObjectCodeCredited { get; set; }
        public string MappingBy { get; set; }
        public DateTime? MappingDate { get; set; }
        public long? FeeTransactiion { get; set; }
        public string SyncAccId { get; set; }
    }
}