// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class BidExternalConfig
    {
        public int Id { get; set; }
        public string YauserName { get; set; }
        public string AccountId { get; set; }
        public string Description { get; set; }
        /// <summary>
        /// 0. Chưa active 1. Active
        /// </summary>
        public int Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}