// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class BuyerConfig
    {
        public int Id { get; set; }
        public string OrderType { get; set; }
        public string Buyer { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string Routes { get; set; }
        public string Domain { get; set; }
    }
}