// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class CustomerPromotion
    {
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string AccountId { get; set; }
    }
}