// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class CustomerNotifyConfig
    {
        public int Id { get; set; }
        public string AppId { get; set; }
        public string AccountId { get; set; }
        public string NotifyConfigCode { get; set; }
        public bool SendEmail { get; set; }
        public bool SendWeb { get; set; }
        public bool SendMobile { get; set; }
        public bool SendDesktop { get; set; }
    }
}