// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class CustomerCode
    {
        public string AccountId { get; set; }
        public string Code { get; set; }
        public int Id { get; set; }
    }
}