// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class CustomerWarehouse
    {
        public int CustomerId { get; set; }
        public int WarehouseId { get; set; }
        public DateTime? ActivationDate { get; set; }
    }
}