// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class DepositMessage
    {
        public int Id { get; set; }
        public string Author { get; set; }
        public string Message { get; set; }
        public int DepositId { get; set; }
        public DateTime CreatedDate { get; set; }
        public string Action { get; set; }

        public virtual Deposits Deposit { get; set; }
    }
}