// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class DepositsEmailNotify
    {
        public int Id { get; set; }
        public long Amount { get; set; }
        public string WalletId { get; set; }
        public long Cash { get; set; }
        public long CashFreeze { get; set; }
        public string AccountId { get; set; }
        public int Sended { get; set; }
        public DateTime? SendDate { get; set; }
        public DateTime CreatedDate { get; set; }
        public string Receiver { get; set; }
        public string ReceiverName { get; set; }
        public string Type { get; set; }
    }
}