// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class EmailMkView
    {
        public string Email { get; set; }
        public string Fullname { get; set; }
    }
}