// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class Fbcomment
    {
        public int Id { get; set; }
        public int FbId { get; set; }
        public string Body { get; set; }
        public string Images { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }

        public virtual Feedback Fb { get; set; }
    }
}