// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class Fbhistory
    {
        public int Id { get; set; }
        public int FbId { get; set; }
        public int? FbType { get; set; }
        public int Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Tracking { get; set; }
        public string OrderCode { get; set; }
        public string Images { get; set; }
        public string Note { get; set; }
        public string Owner { get; set; }
        public string Supporter { get; set; }

        public virtual Feedback Fb { get; set; }
    }
}