// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class Fbpackage
    {
        public Fbpackage()
        {
            Fbpackagedetail = new HashSet<Fbpackagedetail>();
            Fbproduct = new HashSet<Fbproduct>();
            InverseParent = new HashSet<Fbpackage>();
        }

        public int Id { get; set; }
        public int? RefId { get; set; }
        public int? RefPackageId { get; set; }
        public string Code { get; set; }
        public string TrackingCode { get; set; }
        public string TransportCode { get; set; }
        public int? ParentId { get; set; }
        public string Name { get; set; }
        public decimal? Weight { get; set; }
        public decimal? Length { get; set; }
        public decimal? Width { get; set; }
        public decimal? Height { get; set; }
        public int? NoOfPiece { get; set; }
        public decimal? DimensionWeight { get; set; }
        public decimal? CodFee { get; set; }
        public string CodProof { get; set; }
        public string ImageBalanceScale { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public int? Property { get; set; }
        public int Status { get; set; }
        public int? ContainerId { get; set; }
        public int? WarehouseId { get; set; }
        public string WarehouseCode { get; set; }
        public int? FlightId { get; set; }
        public int? BinLocationId { get; set; }
        public string Region { get; set; }
        public string ServiceChargeCode { get; set; }
        public string History { get; set; }
        public string EmployeeHandling { get; set; }
        public DateTime? ProcessedDate { get; set; }
        public int? SyncStatus { get; set; }
        public DateTime? LastSyncDate { get; set; }

        public virtual Fbpackage Parent { get; set; }
        public virtual ICollection<Fbpackagedetail> Fbpackagedetail { get; set; }
        public virtual ICollection<Fbproduct> Fbproduct { get; set; }
        public virtual ICollection<Fbpackage> InverseParent { get; set; }
    }
}