// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class Fbproduct
    {
        public int Id { get; set; }
        public int? SourceId { get; set; }
        public int? RefId { get; set; }
        public string Code { get; set; }
        public int? CategoryId { get; set; }
        public int PackageDetailId { get; set; }
        public int? PackageId { get; set; }
        public int Type { get; set; }
        public int? Origin { get; set; }
        public string OriginCustom { get; set; }
        public string Name { get; set; }
        public string NameCustom { get; set; }
        public string Images { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public decimal? Price { get; set; }
        public decimal? PriceCustom { get; set; }
        public decimal? Tax { get; set; }
        public string ManufacturerPartNumber { get; set; }
        public string UserAgreementText { get; set; }
        public decimal? Weight { get; set; }
        public decimal? Length { get; set; }
        public decimal? Width { get; set; }
        public decimal? Height { get; set; }
        public string Url { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string ProductUnit { get; set; }
        public int? QtyPerUnit { get; set; }
        public string AdminNote { get; set; }
        public string CustomerNote { get; set; }

        public virtual Fbpackage Package { get; set; }
        public virtual Fbpackagedetail PackageDetail { get; set; }
    }
}