// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class Freeze
    {
        public int Id { get; set; }
        public string AccountId { get; set; }
        public string WalletId { get; set; }
        public long Amount { get; set; }
        /// <summary>
        /// BID_VIP,BID,PAY
        /// </summary>
        public string Type { get; set; }
        public string Ref { get; set; }
        public string Description { get; set; }
        /// <summary>
        /// 1: đang tạm giữ, 0 huỷ tạm giữ
        /// </summary>
        public int Status { get; set; }
        /// <summary>
        /// AUC_PRODUCT
        /// </summary>
        public string RefType { get; set; }
        public string Hash { get; set; }
        public byte[] Version { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }

        public virtual Wallet Wallet { get; set; }
    }
}