// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class LevelTranportGroup
    {
        public int LevelId { get; set; }
        public int GroupId { get; set; }
        public long? PriceWeight { get; set; }
        public long? PriceQuantity { get; set; }
        public long? PriceStandard { get; set; }
        public long? PriceJp { get; set; }
        public long? PriceUs { get; set; }
        public long? PriceKr { get; set; }
        public long? PriceAu { get; set; }
        public string GroupCode { get; set; }
        public long? PriceGe { get; set; }
        public long? PriceCn { get; set; }
        public long? Oregon { get; set; }
        public long? Cali { get; set; }
        public long? Kr { get; set; }
        public long? Uk { get; set; }
        public long? De { get; set; }
        public long? Pcsjp { get; set; }
        public long? Hpc { get; set; }
        public long? Jchiba { get; set; }
        public long? Jchiba2 { get; set; }
    }
}