// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class Level
    {
        /// <summary>
        /// Cấp độ
        /// </summary>
        public int Level1 { get; set; }
        /// <summary>
        /// Tên cấp độ
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// Số link đấu tối đa
        /// </summary>
        public int AucMaxbidlink { get; set; }
        /// <summary>
        /// Công mua %
        /// </summary>
        public int Feebuy { get; set; }
        public int? FeebuyAuc { get; set; }
        /// <summary>
        /// Công mua %
        /// </summary>
        public int? FeebuyMer { get; set; }
        /// <summary>
        /// Cước vận chuyển
        /// </summary>
        public long Feetran { get; set; }
        /// <summary>
        /// Phí huỷ đơn Auction
        /// </summary>
        public long AucFeecancel { get; set; }
        public long TotalPaymentYear { get; set; }
        public long? FeeStandard { get; set; }
        public int? FeebuyUs { get; set; }
        public int? FeebuyJp { get; set; }
        public int? FeebuyKr { get; set; }
        public int? FeebuyUk { get; set; }
        public int? FeebuyGe { get; set; }
        public int? FeebuyCn { get; set; }
        public long? FeetranUs { get; set; }
        public long? FeetranJp { get; set; }
        public long? FeetranKr { get; set; }
        public long? FeetranUk { get; set; }
        public long? FeetranGe { get; set; }
        public long? Oregon { get; set; }
        public long? Cali { get; set; }
        public long? Kr { get; set; }
        public long? Uk { get; set; }
        public long? De { get; set; }
        public long? Pcsjp { get; set; }
        public long? Hpc { get; set; }
        public int? FeebuyVc { get; set; }
        public int? PercentBulky { get; set; }
        public long? FeeTranBulky { get; set; }
        public long? Jchiba { get; set; }
        public long? Jchiba2 { get; set; }
    }
}