// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class Metemp
    {
        public string Code { get; set; }
        public int? Jp { get; set; }
        public int? Jpd { get; set; }
        public int? Shipping { get; set; }
    }
}