// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class NotifyConfig1
    {
        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        /// <summary>
        /// Nhóm cấu hình (Enum: NotifyConfigGroup)
        /// </summary>
        public int? GroupType { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
    }
}