// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class NotifyConfig
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int GroupId { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public bool Required { get; set; }

        public virtual NotifyConfigGroup Group { get; set; }
    }
}