// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class NotifyConfigGroup
    {
        public NotifyConfigGroup()
        {
            NotifyConfig = new HashSet<NotifyConfig>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public int Ord { get; set; }
        public string AppId { get; set; }

        public virtual ICollection<NotifyConfig> NotifyConfig { get; set; }
    }
}