// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class OrderProofPayment
    {
        public int OrderId { get; set; }
        public int ProofPaymentId { get; set; }

        public virtual Order Order { get; set; }
        public virtual ProofPayment ProofPayment { get; set; }
    }
}