// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class OrderRevenue
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public string OrderCode { get; set; }
        public string OrderType { get; set; }
        public DateTime RevenueDate { get; set; }
        public string AccountId { get; set; }
        public string ProductTitle { get; set; }
        public string ProductLink { get; set; }
        public string ProductImage { get; set; }
        public long? Price { get; set; }
        public long? Tax { get; set; }
        public long? ShippingFee { get; set; }
        public long? Surcharge { get; set; }
        public string SurchargeNote { get; set; }
        public int? ExchangeRate { get; set; }
        public long? DeliveryFee { get; set; }
        public int? BuyFee { get; set; }
        public long? CancelFee { get; set; }
        public long? ShippingUnitGlobal { get; set; }
        public int? Weight { get; set; }
        public int? Length { get; set; }
        public int? Hight { get; set; }
        public int? Width { get; set; }
        public long? StandardFee { get; set; }
        public long? AddServiceFee { get; set; }
        public string Type { get; set; }
        public int? SyncAccStatus { get; set; }
        public DateTime? SyncAccDate { get; set; }
        public string SyncAccNo { get; set; }
        public string AccDebit { get; set; }
        public string AccCredited { get; set; }
        public string ObjectTypeDebit { get; set; }
        public string ObjectCodeDebit { get; set; }
        public string ObjectTypeCredited { get; set; }
        public string ObjectCodeCredited { get; set; }
        public long? Paid { get; set; }
        public long? TotalPayment { get; set; }
        public long? Total { get; set; }
        public string Mawb { get; set; }
        public string Tracking { get; set; }
        public string SupporterId { get; set; }
        public long? BuyServiceFee { get; set; }

        public virtual Order Order { get; set; }
    }
}