// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class OrderService
    {
        public OrderService()
        {
            OrderServiceMapping = new HashSet<OrderServiceMapping>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long? Price { get; set; }
        public string Unit { get; set; }
        public int? Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string Icon { get; set; }
        public string WarehouseCode { get; set; }
        public int? WarehouseId { get; set; }
        public int? PriceType { get; set; }
        public string CreatedWarehouseCode { get; set; }
        public int? CreatedWarehouseId { get; set; }

        public virtual ICollection<OrderServiceMapping> OrderServiceMapping { get; set; }
    }
}