// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class Order
    {
        public Order()
        {
            OrderMessage = new HashSet<OrderMessage>();
            OrderPackage = new HashSet<OrderPackage>();
            OrderPayimage = new HashSet<OrderPayimage>();
            OrderProofPayment = new HashSet<OrderProofPayment>();
            OrderPurchaseLog = new HashSet<OrderPurchaseLog>();
            OrderRevenue = new HashSet<OrderRevenue>();
            OrderServiceMapping = new HashSet<OrderServiceMapping>();
            OrderTracking = new HashSet<OrderTracking>();
        }

        public int Id { get; set; }
        /// <summary>
        /// Mã tự sinh
        /// </summary>
        public Guid GuidId { get; set; }
        public string Title { get; set; }
        /// <summary>
        /// Nhân viên khai thác
        /// </summary>
        public string Operator { get; set; }
        /// <summary>
        /// Nhân viên kinh doanh
        /// </summary>
        public string Saler { get; set; }
        public int? SalerRating { get; set; }
        public int? SalerReview { get; set; }
        /// <summary>
        /// Sử dụng xác định thông tin khách hàng
        /// </summary>
        public string AccountId { get; set; }
        /// <summary>
        /// Mã kế toán
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// Đơn giá vận chuyển
        /// </summary>
        public long? ShippingUnit { get; set; }
        /// <summary>
        /// Tổng tiền
        /// </summary>
        public long? Total { get; set; }
        public long? PriceExpected { get; set; }
        public string TrackingBox { get; set; }
        /// <summary>
        /// Mã tracking dành cho khách hàng tra cứu đơn hàng
        /// </summary>
        public string Tracking { get; set; }
        public string TrackingBy { get; set; }
        public DateTime? TrackingDate { get; set; }
        public string TrackingTranport { get; set; }
        public string OrderNumber { get; set; }
        /// <summary>
        /// 0: Đang xử lý 1.Chờ đặt cọc 2. Chờ mua hàng 3. Chờ tất toán 4: Đang giao hàng 5.Đã giao hàng 6: Đã huỷ
        /// </summary>
        public int? Status { get; set; }
        /// <summary>
        /// Ghi chú trạng thái
        /// </summary>
        public string StatusNote { get; set; }
        /// <summary>
        /// 1. Đặt hàng thành công. 2-Đang cập nhật. 3- Chờ khách hàng duyệt. 4- Khách hàng đã duyệ. 5-Khách hàng từ chối. 6. Đã được mua. 7 Đến kho Nhật
        /// </summary>
        public int? TrackingStatus { get; set; }
        /// <summary>
        /// Kiểu đơn hàng: AUCTION | SHOPPING | RAKUTEN | AMAZON | MERCARI | TRANSPORT
        /// </summary>
        public string OrderType { get; set; }
        /// <summary>
        /// Ngày mua hàng
        /// </summary>
        public DateTime OrderDate { get; set; }
        public string PaymentBankNumber { get; set; }
        /// <summary>
        /// Phương thức thanh toán 1.Tiền mặt 2.Chuyển khoản 3.Ví Ichiba
        /// </summary>
        public int? PaymentType { get; set; }
        /// <summary>
        /// Thời hạn thanh toán (ngày)
        /// </summary>
        public int? PaymentDuration { get; set; }
        public string DeliveryPartner { get; set; }
        public string DdimportType { get; set; }
        /// <summary>
        /// Hình thức giao hàng. 1. Giao hàng tiêu chuẩn 2. Giao hàng VIP
        /// </summary>
        public int? DeliveryType { get; set; }
        /// <summary>
        /// Ngày dự kiến giao hàng
        /// </summary>
        public DateTime? DeliveryExpected { get; set; }
        /// <summary>
        /// Ngày  giao hàng
        /// </summary>
        public DateTime? DeliveryDate { get; set; }
        public DateTime? DeliveredDate { get; set; }
        public long? DeliveryCod { get; set; }
        public string DeliveryCode { get; set; }
        /// <summary>
        /// Phí giao hàng tại Việt Nam
        /// </summary>
        public long? DeliveryFee { get; set; }
        /// <summary>
        /// Phí giao hàng tại Việt Nam
        /// </summary>
        public bool? DeliveryPayType { get; set; }
        /// <summary>
        /// % giảm phí giao hàng
        /// </summary>
        public int? DeliveryDiscount { get; set; }
        public int? DeliverySyncStatus { get; set; }
        public DateTime? DeliverySyncWh { get; set; }
        /// <summary>
        /// Phụ phí
        /// </summary>
        public DateTime? SurchargeDate { get; set; }
        public string SurchargeBy { get; set; }
        public string SurchargePay { get; set; }
        /// <summary>
        /// Phụ phí
        /// </summary>
        public long? Surcharge { get; set; }
        public string SurchargeNote { get; set; }
        /// <summary>
        /// Người đặt hàng
        /// </summary>
        public string CustomerDistrict { get; set; }
        /// <summary>
        /// Địa chỉ nhận hàng
        /// </summary>
        public string CustomerAddress { get; set; }
        /// <summary>
        /// Số phone nhận hàng
        /// </summary>
        public string CustomerPhone { get; set; }
        /// <summary>
        /// Tên người nhận hàng
        /// </summary>
        public string CustomerName { get; set; }
        public string CustomerProvince { get; set; }
        public string CustomerWard { get; set; }
        /// <summary>
        /// 0: Đang xử lý 1.Chờ đặt cọc 2. Chờ mua hàng 3. Chờ tất toán 4: Đang giao hàng 5.Đã giao hàng 6: Đã huỷ
        /// </summary>
        public string State { get; set; }
        /// <summary>
        /// Ghi chú
        /// </summary>
        public string Note { get; set; }
        /// <summary>
        /// % yêu cầu thanh toán tối thiểu
        /// </summary>
        public int? MinPayment { get; set; }
        /// <summary>
        /// Đã thanh toán
        /// </summary>
        public long? Paid { get; set; }
        public string Hash { get; set; }
        /// <summary>
        /// Phí mua hộ
        /// </summary>
        public long? BuyFee { get; set; }
        /// <summary>
        /// Phụ phí
        /// </summary>
        public DateTime? ShippingFeeDate { get; set; }
        public string ShippingFeeBy { get; set; }
        /// <summary>
        /// Phí vận chuyển nội địa Nhật
        /// </summary>
        public long? ShippingFee { get; set; }
        /// <summary>
        /// Phí vận chuyển về VN
        /// </summary>
        public long? ShippingFeeToLocal { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ProcessDate { get; set; }
        public byte[] Version { get; set; }
        public string Warehouse { get; set; }
        public string Type { get; set; }
        /// <summary>
        /// Trọng lượng (gam)
        /// </summary>
        public int? Weight { get; set; }
        public int? WeightOrigin { get; set; }
        /// <summary>
        /// Chiều rộng (cm)
        /// </summary>
        public int? Width { get; set; }
        /// <summary>
        /// Chiều cao (cm)
        /// </summary>
        public int? Hight { get; set; }
        /// <summary>
        /// Chiều dài (cm)
        /// </summary>
        public int? Length { get; set; }
        /// <summary>
        /// Tỉ giá
        /// </summary>
        public int? ExchangeRate { get; set; }
        /// <summary>
        /// Đơn giá vận chuyển quốc tế
        /// </summary>
        public int? ShippingUnitGlobal { get; set; }
        public string PaymentAccount { get; set; }
        public string BidAccount { get; set; }
        public DateTime? LastSyncWh { get; set; }
        public long? TotalPayment { get; set; }
        public DateTime? EstimateTime { get; set; }
        public DateTime? LastActionDate { get; set; }
        public string LastAction { get; set; }
        public bool? Yacomplete { get; set; }
        public bool? Cod { get; set; }
        public string ProductType { get; set; }
        public bool? Negotiate { get; set; }
        public bool? BidStatus { get; set; }
        public string Images { get; set; }
        public string Payer { get; set; }
        public string PurchaseBy { get; set; }
        public DateTime? PurchaseDate { get; set; }
        public string CancelBy { get; set; }
        public DateTime? CancelDate { get; set; }
        public DateTime? CancelApproveDate { get; set; }
        public string CancelApproveBy { get; set; }
        public string AccDebit { get; set; }
        public string AccCredited { get; set; }
        public int? SyncAccStatus { get; set; }
        public DateTime? SyncAccDate { get; set; }
        public string SyncAccNo { get; set; }
        public long? StandardFee { get; set; }
        public long? AddServiceFee { get; set; }
        public DateTime? WfProcess { get; set; }
        public DateTime? CompleteDate { get; set; }
        public int? RevenueStatus { get; set; }
        public string QuoteCode { get; set; }
        public DateTime? QuoteDate { get; set; }
        public long? TotalServiceFee { get; set; }
        public string FromRoute { get; set; }
        public string Currency { get; set; }
        public string Supporter { get; set; }
        public int? CustomerRatting { get; set; }
        public DateTime? CustomerRattingDate { get; set; }
        public DateTime? WaitQuoteDate { get; set; }
        public string WhImporter { get; set; }
        public string WhExporter { get; set; }
        public string Mawb { get; set; }
        public int? TransportPaymentType { get; set; }
        public string PurchaseAssign { get; set; }
        public DateTime? RevenueDate { get; set; }
        public int? ShippingRouteId { get; set; }
        public string ShippingRouteCode { get; set; }
        public string GroupOrder { get; set; }
        public int? ToWarehouseId { get; set; }
        public string ToWarehouseCode { get; set; }
        public long? BuyServiceFee { get; set; }
        public DateTime? DepartureDate { get; set; }
        public bool? Bulky { get; set; }
        public string ProductByCustomerJson { get; set; }
        public int? PurchaseConfirmationStatus { get; set; }

        public virtual ICollection<OrderMessage> OrderMessage { get; set; }
        public virtual ICollection<OrderPackage> OrderPackage { get; set; }
        public virtual ICollection<OrderPayimage> OrderPayimage { get; set; }
        public virtual ICollection<OrderProofPayment> OrderProofPayment { get; set; }
        public virtual ICollection<OrderPurchaseLog> OrderPurchaseLog { get; set; }
        public virtual ICollection<OrderRevenue> OrderRevenue { get; set; }
        public virtual ICollection<OrderServiceMapping> OrderServiceMapping { get; set; }
        public virtual ICollection<OrderTracking> OrderTracking { get; set; }
    }
}