// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class OrderComMoney
    {
        public long Id { get; set; }
        public int OrderComId { get; set; }
        public string OrderCode { get; set; }
        public string EmployeeId { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public DateTime ComDate { get; set; }
        public long? ComMoney { get; set; }
        public string ComMoneyType { get; set; }
        public int? Status { get; set; }
        public string ComSource { get; set; }

        public virtual OrderCom OrderCom { get; set; }
    }
}