// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class OrderPurchaseLog
    {
        public int Id { get; set; }
        public string ActionBy { get; set; }
        public DateTime ActionDate { get; set; }
        public string ActionType { get; set; }
        public string CreatedBy { get; set; }
        public int OrderId { get; set; }
        public long? Price { get; set; }
        public long? Tax { get; set; }
        public long? ShippingFee { get; set; }
        public long? Surcharge { get; set; }
        public int? ExchangeRate { get; set; }
        public int? Status { get; set; }

        public virtual Order Order { get; set; }
    }
}