// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class OrderImportTemp
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Link { get; set; }
        public string OrderType { get; set; }
        public string Title { get; set; }
        public string NoteOrder { get; set; }
        public int? Amount { get; set; }
        public long? Price { get; set; }
        public int? Tax { get; set; }
        public string ShippingFee { get; set; }
        public string CustomerName { get; set; }
        public string Tracking { get; set; }
        public string Note { get; set; }
        public string CustomerCode { get; set; }
    }
}