// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class OrderTracking
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        /// <summary>
        /// 0. Đặt hàng thành công 1. Đã cọc thanh toán 2. Hàng đang chuyển tới kho Nhật 3. Hàng về kho ViệtNam 4.Tất toán 5.Giao hàng 6.Đã giao hàng 7.Huỷ
        /// </summary>
        public int Status { get; set; }
        public string Note { get; set; }
        public DateTime CreatedDate { get; set; }
        public string Description { get; set; }
        public string PackageCode { get; set; }
        public string WarehouseCode { get; set; }
        public DateTime NotifyDate { get; set; }
        public string FromWarehouseCode { get; set; }
        public string ToWarehouseCode { get; set; }

        public virtual Order Order { get; set; }
    }
}