// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class OrderPackage
    {
        public OrderPackage()
        {
            OrderPackageProduct = new HashSet<OrderPackageProduct>();
        }

        public int Id { get; set; }
        public string Code { get; set; }
        /// <summary>
        /// Trọng lượng (gam)
        /// </summary>
        public int? Weight { get; set; }
        /// <summary>
        /// Chiều rộng (cm)
        /// </summary>
        public int? Width { get; set; }
        /// <summary>
        /// Chiều cao (cm)
        /// </summary>
        public int? Height { get; set; }
        /// <summary>
        /// Chiều dài (cm)
        /// </summary>
        public int? Length { get; set; }
        public int? OrderId { get; set; }
        public string Image { get; set; }
        public long? TotalPayment { get; set; }
        public int? WeightType { get; set; }

        public virtual Order Order { get; set; }
        public virtual ICollection<OrderPackageProduct> OrderPackageProduct { get; set; }
    }
}