// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class PackageTracking
    {
        public int Id { get; set; }
        public string Tracking { get; set; }
        public string FromWarehouseCode { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public DateTime NotifyDate { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ToWarehouseCode { get; set; }
    }
}