// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class Payforbuyer
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public long Amount { get; set; }
        public decimal ExchangeRate { get; set; }
        public DateTime PayDate { get; set; }
        public string Description { get; set; }
        public string SupplierId { get; set; }
        public string SupplierCode { get; set; }
        public string Note { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string AccDebit { get; set; }
        public string AccCredited { get; set; }
        public string ObjectTypeDebit { get; set; }
        public string ObjectCodeDebit { get; set; }
        public string ObjectTypeCredited { get; set; }
        public string ObjectCodeCredited { get; set; }
        public int? SyncAccStatus { get; set; }
        public DateTime? SyncAccDate { get; set; }
        public string SyncAccNo { get; set; }
        public int? Status { get; set; }
        public string Ftcode { get; set; }
        public DateTime? ProcessDate { get; set; }
    }
}