// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class PaymentAccount
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}