// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class ProductType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string TitleEn { get; set; }
        public string TitleJa { get; set; }
        public string Elements { get; set; }
        public string ElementsEn { get; set; }
        public string ElementsJa { get; set; }
        public string Description { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public int? Ord { get; set; }
        public int? GroupId { get; set; }
        public long? PriceStandard { get; set; }
        public long? PriceStandardUs { get; set; }
        public long? PriceStandardJp { get; set; }
        public long? PriceStandardKr { get; set; }
        public long? PriceStandardUk { get; set; }
        public long? PriceStandardGe { get; set; }

        public virtual ProductTypeGroup Group { get; set; }
    }
}