// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class ProofPayment
    {
        public ProofPayment()
        {
            OrderProofPayment = new HashSet<OrderProofPayment>();
        }

        public int Id { get; set; }
        public string Image { get; set; }
        public DateTime CreatedDate { get; set; }
        public string AccountId { get; set; }

        public virtual ICollection<OrderProofPayment> OrderProofPayment { get; set; }
    }
}