// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class PurchaseReportData
    {
        public int Id { get; set; }
        public int ReportId { get; set; }
        public DateTime PaymentDate { get; set; }
        public DateTime? CancelDate { get; set; }
        public string CancelBy { get; set; }
        public DateTime? ActionDate { get; set; }
        public string ActionBy { get; set; }
        public string PaymentBy { get; set; }
        public string PaymentType { get; set; }
        public string AccountId { get; set; }
        public string OrderCode { get; set; }
        public string ProductTitle { get; set; }
        public string ProductLink { get; set; }
        public string ProductImage { get; set; }
        public long? Price { get; set; }
        public int? Tax { get; set; }
        public long? ShippingFee { get; set; }
        public bool? ShippingCod { get; set; }
        public string Warehouse { get; set; }
        public long? DebitAmount { get; set; }
        public long? CreditAmount { get; set; }
        public long? Surcharge { get; set; }
        public string SurchargeNote { get; set; }
        public string Type { get; set; }
        public string CareBy { get; set; }

        public virtual PurchaseReport Report { get; set; }
    }
}