// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class PurchaseReport
    {
        public PurchaseReport()
        {
            PurchaseReportData = new HashSet<PurchaseReportData>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int Status { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string SyncBy { get; set; }
        public DateTime? SyncDate { get; set; }
        public string Type { get; set; }
        public bool? Lock { get; set; }

        public virtual ICollection<PurchaseReportData> PurchaseReportData { get; set; }
    }
}