// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class Successfulbid
    {
        public string Id { get; set; }
        public string YauserName { get; set; }
        public string Title { get; set; }
        public long Price { get; set; }
        public string SellerId { get; set; }
        public string EndDateAndTime { get; set; }
        public string LastMessage { get; set; }
        public long Order { get; set; }
        public string AccountId { get; set; }
        public DateTime? EndDate { get; set; }
        public long? BidPrice { get; set; }
        public int? Quantity { get; set; }
        public int? Bids { get; set; }
        public int MapStatus { get; set; }
        public DateTime? BidTime { get; set; }
        public string YauserNameBidSystem { get; set; }
        public string PreviewImage { get; set; }
        public string Images { get; set; }
        public string CategoryCode { get; set; }
        public decimal? JpyRate { get; set; }
        public string Code { get; set; }
        public int? Tax { get; set; }
        public DateTime? CreatedDate { get; set; }
        public bool? CreatedOrder { get; set; }
        public int? PaymentStatus { get; set; }
        public int? FeeBuy { get; set; }
        public bool? Cached { get; set; }
        public long? ShippingFee { get; set; }
    }
}