// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class Supplier
    {
        public int Id { get; set; }
        public string Uid { get; set; }
        /// <summary>
        /// Tên KH/NCC
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Mã KH/NCC
        /// </summary>
        public string Code { get; set; }
        /// <summary>
        /// Quốc gia
        /// </summary>
        public string Country { get; set; }
        /// <summary>
        /// Tỉnh
        /// </summary>
        public string Province { get; set; }
        /// <summary>
        /// Huyện
        /// </summary>
        public string District { get; set; }
        /// <summary>
        /// Xã/Phưởng
        /// </summary>
        public string Commune { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Website { get; set; }
        public string Identify { get; set; }
        public DateTime? IdIssuedDate { get; set; }
        public string IdIssuedBy { get; set; }
        public int? Gender { get; set; }
        public string Email { get; set; }
        public string TaxCode { get; set; }
        public string Represent { get; set; }
        public int? RepGender { get; set; }
        public string RepTitle { get; set; }
        public string RepPhone { get; set; }
        public string RepMobile { get; set; }
        public string RepEmail { get; set; }
        public string BankNumber { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string BankProvince { get; set; }
        public bool? Active { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public int? SyncAccStatus { get; set; }
        public DateTime? SyncAccDate { get; set; }
        public string AccountId { get; set; }
        public int? Buyer { get; set; }
        public string WhCode { get; set; }
        public long? BeginBalance { get; set; }
        public DateTime? BeginBalanceDate { get; set; }
    }
}