// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class SurveyProductTypeGroup
    {
        public string Id { get; set; }
        public int CustomerId { get; set; }
        public string UserId { get; set; }
        public int ProductTypeGroupId { get; set; }
        public bool Active { get; set; }
        public int DisplayOrder { get; set; }

        public virtual Customer Customer { get; set; }
    }
}