// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class SyncData
    {
        public int Id { get; set; }
        public string TrackingCode { get; set; }
        public string OrderCode { get; set; }
        public string QuoteCode { get; set; }
        public DateTime SyncDate { get; set; }
        public bool? Ignore { get; set; }
        public string Note { get; set; }
        public string Json { get; set; }
        public int DataType { get; set; }
    }
}