// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class SyncBankTransactionHistory
    {
        public int Id { get; set; }
        public string Ftcode { get; set; }
        public DateTime? SyncAccDate { get; set; }
        public int? SyncAccStatus { get; set; }
        public string SyncAccNo { get; set; }
        public DateTime TransactionDate { get; set; }
        public long Amount { get; set; }
        public string AccountNumber { get; set; }
        public string CreditOwner { get; set; }
        public string BankType { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public string TransactionType { get; set; }
        public string AccDebit { get; set; }
        public string AccCredited { get; set; }
        public string ObjectTypeDebit { get; set; }
        public string ObjectCodeDebit { get; set; }
        public string ObjectTypeCredited { get; set; }
        public string ObjectCodeCredited { get; set; }
        public string MappingBy { get; set; }
        public DateTime? MappingDate { get; set; }
    }
}