// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class Withdrawal
    {
        public Withdrawal()
        {
            WithdrawalMessage = new HashSet<WithdrawalMessage>();
        }

        public int Id { get; set; }
        /// <summary>
        /// Số tiền
        /// </summary>
        public long Amount { get; set; }
        public long? Fee { get; set; }
        public string AccountId { get; set; }
        public string BankNumber { get; set; }
        public string BankAccountName { get; set; }
        public string BankName { get; set; }
        public string BankProvince { get; set; }
        public string BankBranch { get; set; }
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// TT rút tiền (0. Chờ xử lý 1.Đã chuyển tiền  2. Đã huỷ )
        /// </summary>
        public int WithDrawalStatus { get; set; }
        /// <summary>
        /// TT xác nhận (0. Chờ xác nhận 1. Đã xác nhận)
        /// </summary>
        public int ConfirmStatus { get; set; }
        public string Hash { get; set; }
        public string WalletId { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ProcessDate { get; set; }
        public byte[] Version { get; set; }
        public string Note { get; set; }
        public string ProofImage { get; set; }
        public string Type { get; set; }
        public string State { get; set; }
        public string Code { get; set; }
        public string Ftcode { get; set; }
        /// <summary>
        /// BANK | ICHIBA
        /// </summary>
        public string WithDrawalType { get; set; }
        public string BankContent { get; set; }
        public DateTime? BankDate { get; set; }

        public virtual Wallet Wallet { get; set; }
        public virtual ICollection<WithdrawalMessage> WithdrawalMessage { get; set; }
    }
}