// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class WorkflowHistory
    {
        public int Id { get; set; }
        public DateTime Created { get; set; }
        public string FromState { get; set; }
        public string ToState { get; set; }
        public string UserName { get; set; }
        public int WorkflowId { get; set; }

        public virtual Workflow Workflow { get; set; }
    }
}