// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace iChiba.OM.Model
{
    public partial class WorkflowVariable
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Content { get; set; }
        public int WorkflowId { get; set; }

        public virtual Workflow Workflow { get; set; }
    }
}