// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace iChiba.DC.Model
{
    public partial class BidConfig
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Alias { get; set; }
        public string Password { get; set; }
        public string GroupKey { get; set; }
        public int? Status { get; set; }
        public DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string Buyer { get; set; }
    }
}