// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace iChiba.DC.Model
{
    public partial class Exchangerates
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public double? Buy { get; set; }
        public double? Transfer { get; set; }
        public double? Sell { get; set; }
        public double? Add { get; set; }
    }
}