// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace iChiba.DC.Model
{
    public partial class Languages
    {
        public Languages()
        {
            Localeresources = new HashSet<Localeresources>();
            Localizedproperties = new HashSet<Localizedproperties>();
        }

        public string Id { get; set; }
        public string Title { get; set; }
        public bool? Published { get; set; }
        public int? Order { get; set; }

        public virtual ICollection<Localeresources> Localeresources { get; set; }
        public virtual ICollection<Localizedproperties> Localizedproperties { get; set; }
    }
}