// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace iChiba.DC.Model
{
    public partial class Locations
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int? Parent { get; set; }
        public string Vtkey { get; set; }
        public string Emskey { get; set; }
        public string Vnpkey { get; set; }
        public string Contry { get; set; }
        public string Area { get; set; }
    }
}