// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace iChiba.DC.Model
{
    public partial class Store_CollectOrderTypeResult
    {
        public string OrderType { get; set; }
    }
}
